In [1]:
import pandas as pd
import numpy as np

%matplotlib inline
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('B_dataset_clean_v1.csv')

In [2]:
# Take a random sample of 10,000 rows
#df = df.sample(n=50000, random_state=42)

# Display the sampled dataset
#df.head()

In [3]:
df.dtypes

ticket_id               int64
id_customer             int64
date                   object
store_id                int64
store_type             object
PL_gross_sales        float64
net_sales             float64
gross_sales           float64
number_items_other      int64
number_item_PL          int64
dtype: object

In [4]:
df['date'] = df['date'].astype(str).str.strip()

# Convert to datetime without coercion
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d', errors='raise')

In [5]:
df

,ticket_id,id_customer,date,store_id,store_type,PL_gross_sales,net_sales,gross_sales,number_items_other,number_item_PL
0,1375818,21169,2021-12-22,1156,superstore,0.00,12.99,12.99,1,0
1,1375821,21172,2021-12-22,1018,superstore,10.24,37.91,41.93,12,8
2,1375822,21173,2021-12-22,1038,superstore,14.80,59.81,67.78,15,4
3,1375823,21174,2021-12-22,1065,superstore,14.68,66.59,68.79,12,3
4,1375825,21177,2021-12-22,1164,superstore,8.58,8.58,8.58,0,1
...,...,...,...,...,...,...,...,...,...,...
2071162,1375804,21157,2021-12-22,1043,superstore,22.60,44.41,54.15,14,5
2071163,1375805,21159,2021-12-22,1033,superstore,7.33,24.66,2.65,9,2
2071164,1375806,21160,2021-12-22,1177,superstore,4.71,0.67,0.67,1,2
2071165,1375807,21160,2021-12-22,1177,superstore,36.21,71.82,73.82,9,3
2071166,1375813,21162,2021-12-22,1047,superstore,72.43,212.76,265.74,38,14

In [11]:
df.dtypes

ticket_id                      int64
id_customer                    int64
date                  datetime64[ns]
store_id                       int64
store_type                    object
PL_gross_sales               float64
net_sales                    float64
gross_sales                  float64
number_items_other             int64
number_item_PL                 int64
dtype: object

In [13]:
df.isnull().sum()

ticket_id             0
id_customer           0
date                  0
store_id              0
store_type            0
PL_gross_sales        0
net_sales             0
gross_sales           0
number_items_other    0
number_item_PL        0
dtype: int64

In [15]:
df[df['net_sales'] < 0]

Empty DataFrame
Columns: [ticket_id, id_customer, date, store_id, store_type, PL_gross_sales, net_sales, gross_sales, number_items_other, number_item_PL]
Index: []

In [17]:
df[df['gross_sales'] <0]

Empty DataFrame
Columns: [ticket_id, id_customer, date, store_id, store_type, PL_gross_sales, net_sales, gross_sales, number_items_other, number_item_PL]
Index: []

In [19]:
df.isnull().sum()

ticket_id             0
id_customer           0
date                  0
store_id              0
store_type            0
PL_gross_sales        0
net_sales             0
gross_sales           0
number_items_other    0
number_item_PL        0
dtype: int64

In [21]:
df

,ticket_id,id_customer,date,store_id,store_type,PL_gross_sales,net_sales,gross_sales,number_items_other,number_item_PL
0,1375818,21169,2021-12-22,1156,superstore,0.00,12.99,12.99,1,0
1,1375821,21172,2021-12-22,1018,superstore,10.24,37.91,41.93,12,8
2,1375822,21173,2021-12-22,1038,superstore,14.80,59.81,67.78,15,4
3,1375823,21174,2021-12-22,1065,superstore,14.68,66.59,68.79,12,3
4,1375825,21177,2021-12-22,1164,superstore,8.58,8.58,8.58,0,1
...,...,...,...,...,...,...,...,...,...,...
2071162,1375804,21157,2021-12-22,1043,superstore,22.60,44.41,54.15,14,5
2071163,1375805,21159,2021-12-22,1033,superstore,7.33,24.66,2.65,9,2
2071164,1375806,21160,2021-12-22,1177,superstore,4.71,0.67,0.67,1,2
2071165,1375807,21160,2021-12-22,1177,superstore,36.21,71.82,73.82,9,3
2071166,1375813,21162,2021-12-22,1047,superstore,72.43,212.76,265.74,38,14

In [23]:

# Group by Customer_id and DATE
grouped = df.groupby(['id_customer', 'date']).apply(
    lambda group: pd.Series({
        
        'Gross_sales': group['gross_sales'].sum(),
        'Net_sales': group['net_sales'].sum(),
        'PL_gross_sales': group['PL_gross_sales'].sum()
        
      
          # Sum total sales after the calculations
    })
).reset_index()

# Display the grouped DataFrame
print(grouped)

         id_customer       date  Gross_sales  Net_sales  PL_gross_sales
0                  1 2021-01-04        85.62      73.11            2.44
1                  1 2021-01-08        13.44      13.44            0.09
2                  1 2021-01-19        25.94      19.03           21.50
3                  1 2021-02-05         9.47       9.47            1.59
4                  1 2021-02-27        31.41      29.52            3.95
...              ...        ...          ...        ...             ...
1861946        25000 2021-10-27        18.46     164.41           52.49
1861947        25000 2021-11-11       171.38      15.63           40.46
1861948        25000 2021-11-25       130.72     120.12           52.76
1861949        25000 2021-12-09       186.67     171.42           54.38
1861950        25000 2021-12-22       141.64     125.78           49.48

[1861951 rows x 5 columns]

C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\2761214216.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped = df.groupby(['id_customer', 'date']).apply(

In [24]:
total_sales = pd.DataFrame(grouped)

In [29]:
total_sales

         id_customer       date  Gross_sales  Net_sales  PL_gross_sales
0                  1 2021-01-04        85.62      73.11            2.44
1                  1 2021-01-08        13.44      13.44            0.09
2                  1 2021-01-19        25.94      19.03           21.50
3                  1 2021-02-05         9.47       9.47            1.59
4                  1 2021-02-27        31.41      29.52            3.95
...              ...        ...          ...        ...             ...
1861946        25000 2021-10-27        18.46     164.41           52.49
1861947        25000 2021-11-11       171.38      15.63           40.46
1861948        25000 2021-11-25       130.72     120.12           52.76
1861949        25000 2021-12-09       186.67     171.42           54.38
1861950        25000 2021-12-22       141.64     125.78           49.48

[1861951 rows x 5 columns]

In [31]:
latest_date = total_sales['date'].max()
latest_date

Timestamp('2021-12-31 00:00:00')

In [35]:
import pandas as pd

# Ensure the 'date' column is in datetime format
total_sales['date'] = pd.to_datetime(total_sales['date'])

# Define the latest date for calculating recency
latest_date = total_sales['date'].max()

# Perform RFM analysis
rfm_analysis = total_sales.groupby('id_customer').agg(
    Recency=('date', lambda x: (latest_date - x.max()).days),  # Recency: Days since last purchase
    Frequency=('date', 'count'),  # Frequency: Number of transactions
    Monetary=('Gross_sales', 'sum'),  # Monetary: Total spending
    Monetary_net=('Net_sales', 'sum'),
    Monetary_PL=('PL_gross_sales','sum'),
    First_Purchase=('date', 'min'),  # First purchase date
    Last_Purchase=('date', 'max')   # Last purchase date
)

# Add inter-purchase metrics for customers with more than one purchase
rfm_analysis['Avg_Interpurchase_Time'] = total_sales.groupby('id_customer')['date'].apply(
    lambda x: (x.sort_values().diff().dt.days.mean() if len(x) > 1 else None)
).values

rfm_analysis['Std_Dev_Interpurchase_Time'] = total_sales.groupby('id_customer')['date'].apply(
    lambda x: (x.sort_values().diff().dt.days.std() if len(x) > 1 else None)
).values

# Add ticket-level metrics
rfm_analysis['Avg_Ticket'] = total_sales.groupby('id_customer')['Gross_sales'].mean().values
rfm_analysis['Std_Dev_Ticket'] = total_sales.groupby('id_customer')['Gross_sales'].std().values

# Reset index to make it a flat DataFrame
rfm_analysis = rfm_analysis.reset_index()

# Display the RFM analysis
print(rfm_analysis)

       id_customer  Recency  Frequency  Monetary  Monetary_net  Monetary_PL  \
0                1        0         41    900.91        827.80       177.20
1                2        4         50   1229.57        980.41       404.31
2                3        8         20   1568.19       1083.57        56.00
3                4        0         74   4063.11       3348.90       865.91
4                5        2        121   5016.60       4331.09       651.12
...            ...      ...        ...       ...           ...          ...
24994        24996        0        221   3074.26       2975.11      1645.51
24995        24997        0        277   3333.95       2936.30      1263.56
24996        24998        0         90   3722.30       3192.02      1346.93
24997        24999        0        261  10022.70       8256.64      2938.74
24998        25000        9         36   3166.14       2849.25       775.18

      First_Purchase Last_Purchase  Avg_Interpurchase_Time  \
0         2021-01-04    2021-12-31                9.025000
1         2021-01-11    2021-12-27                7.142857
2         2021-01-03    2021-12-23               18.631579
3         2021-01-02    2021-12-31                4.972603
4         2021-01-02    2021-12-29                3.008333
...              ...           ...                     ...
24994     2021-01-03    2021-12-31                1.645455
24995     2021-01-02    2021-12-31                1.315217
24996     2021-01-05    2021-12-31                4.044944
24997     2021-01-02    2021-12-31                1.396154
24998     2021-01-04    2021-12-22               10.057143

       Std_Dev_Interpurchase_Time  Avg_Ticket  Std_Dev_Ticket
0                       10.146333   21.973415       16.485270
1                        4.743416   24.591400       22.680259
2                       18.160429   78.409500      124.179337
3                        2.876980   54.906892       37.033964
4                        2.911859   41.459504       37.598486
...                           ...         ...             ...
24994                    1.502426   13.910679       13.037960
24995                    1.392938   12.035921        8.590344
24996                    2.499591   41.358889       28.744819
24997                    0.634273   38.401149       38.371012
24998                    5.583288   87.948333       59.073081

[24999 rows x 12 columns]

In [51]:
rfm = pd.DataFrame(rfm_analysis)
rfm

,id_customer,Recency,Frequency,Monetary,Monetary_net,Monetary_PL,First_Purchase,Last_Purchase,Avg_Interpurchase_Time,Std_Dev_Interpurchase_Time,Avg_Ticket,Std_Dev_Ticket
0,1,0,41,900.91,827.80,177.20,2021-01-04,2021-12-31,9.025000,10.146333,21.973415,16.485270
1,2,4,50,1229.57,980.41,404.31,2021-01-11,2021-12-27,7.142857,4.743416,24.591400,22.680259
2,3,8,20,1568.19,1083.57,56.00,2021-01-03,2021-12-23,18.631579,18.160429,78.409500,124.179337
3,4,0,74,4063.11,3348.90,865.91,2021-01-02,2021-12-31,4.972603,2.876980,54.906892,37.033964
4,5,2,121,5016.60,4331.09,651.12,2021-01-02,2021-12-29,3.008333,2.911859,41.459504,37.598486
...,...,...,...,...,...,...,...,...,...,...,...,...
24994,24996,0,221,3074.26,2975.11,1645.51,2021-01-03,2021-12-31,1.645455,1.502426,13.910679,13.037960
24995,24997,0,277,3333.95,2936.30,1263.56,2021-01-02,2021-12-31,1.315217,1.392938,12.035921,8.590344
24996,24998,0,90,3722.30,3192.02,1346.93,2021-01-05,2021-12-31,4.044944,2.499591,41.358889,28.744819
24997,24999,0,261,10022.70,8256.64,2938.74,2021-01-02,2021-12-31,1.396154,0.634273,38.401149,38.371012
24998,25000,9,36,3166.14,2849.25,775.18,2021-01-04,2021-12-22,10.057143,5.583288,87.948333,59.073081

In [53]:
df[df['id_customer'] =='3'	]['date']# which means that frequency is number of unique date

Series([], Name: date, dtype: datetime64[ns])

In [55]:
rfm[rfm['id_customer'] =='3']

Empty DataFrame
Columns: [id_customer, Recency, Frequency, Monetary, Monetary_net, Monetary_PL, First_Purchase, Last_Purchase, Avg_Interpurchase_Time, Std_Dev_Interpurchase_Time, Avg_Ticket, Std_Dev_Ticket]
Index: []

In [57]:
rfm[rfm['Frequency'] ==1]

Empty DataFrame
Columns: [id_customer, Recency, Frequency, Monetary, Monetary_net, Monetary_PL, First_Purchase, Last_Purchase, Avg_Interpurchase_Time, Std_Dev_Interpurchase_Time, Avg_Ticket, Std_Dev_Ticket]
Index: []

In [59]:
rfm_analysis= rfm[rfm['Frequency'] > 1]

In [61]:
rfm_analysis

,id_customer,Recency,Frequency,Monetary,Monetary_net,Monetary_PL,First_Purchase,Last_Purchase,Avg_Interpurchase_Time,Std_Dev_Interpurchase_Time,Avg_Ticket,Std_Dev_Ticket
0,1,0,41,900.91,827.80,177.20,2021-01-04,2021-12-31,9.025000,10.146333,21.973415,16.485270
1,2,4,50,1229.57,980.41,404.31,2021-01-11,2021-12-27,7.142857,4.743416,24.591400,22.680259
2,3,8,20,1568.19,1083.57,56.00,2021-01-03,2021-12-23,18.631579,18.160429,78.409500,124.179337
3,4,0,74,4063.11,3348.90,865.91,2021-01-02,2021-12-31,4.972603,2.876980,54.906892,37.033964
4,5,2,121,5016.60,4331.09,651.12,2021-01-02,2021-12-29,3.008333,2.911859,41.459504,37.598486
...,...,...,...,...,...,...,...,...,...,...,...,...
24994,24996,0,221,3074.26,2975.11,1645.51,2021-01-03,2021-12-31,1.645455,1.502426,13.910679,13.037960
24995,24997,0,277,3333.95,2936.30,1263.56,2021-01-02,2021-12-31,1.315217,1.392938,12.035921,8.590344
24996,24998,0,90,3722.30,3192.02,1346.93,2021-01-05,2021-12-31,4.044944,2.499591,41.358889,28.744819
24997,24999,0,261,10022.70,8256.64,2938.74,2021-01-02,2021-12-31,1.396154,0.634273,38.401149,38.371012
24998,25000,9,36,3166.14,2849.25,775.18,2021-01-04,2021-12-22,10.057143,5.583288,87.948333,59.073081

In [63]:
rfm_analysis.isnull().sum()

id_customer                     0
Recency                         0
Frequency                       0
Monetary                        0
Monetary_net                    0
Monetary_PL                     0
First_Purchase                  0
Last_Purchase                   0
Avg_Interpurchase_Time          0
Std_Dev_Interpurchase_Time    148
Avg_Ticket                      0
Std_Dev_Ticket                  0
dtype: int64

In [69]:
percentiles = {
    'Frequency': {
        95: rfm_analysis['Frequency'].quantile(0.95),
        96: rfm_analysis['Frequency'].quantile(0.96),
        97: rfm_analysis['Frequency'].quantile(0.97),
        98: rfm_analysis['Frequency'].quantile(0.98),
        99: rfm_analysis['Frequency'].quantile(0.99),
    },
    'Monetary': {
        95: rfm_analysis['Monetary'].quantile(0.95),
        96: rfm_analysis['Monetary'].quantile(0.96),
        97: rfm_analysis['Monetary'].quantile(0.97),
        98: rfm_analysis['Monetary'].quantile(0.98),
        99: rfm_analysis['Monetary'].quantile(0.99),
    }
}
# Adjusted anomaly threshold to 30%
def check_anomaly_threshold(percentile_dict, threshold=0.5):
    values = list(percentile_dict.values())
    diffs = np.diff(values) / np.array(values[:-1])
    return diffs > threshold

frequency_anomalies = check_anomaly_threshold(percentiles['Frequency'], threshold=0.5)
monetary_anomalies = check_anomaly_threshold(percentiles['Monetary'], threshold=0.5)

# Set thresholds again
frequency_threshold = (
    list(percentiles['Frequency'].values())[-1]
    if any(frequency_anomalies) else None
)
monetary_threshold = (
    list(percentiles['Monetary'].values())[-1]
    if any(monetary_anomalies) else None
)

print("Adjusted Frequency Anomalies Detected:", frequency_anomalies)
print("Adjusted Monetary Anomalies Detected:", monetary_anomalies)
print("Adjusted Frequency Threshold:", frequency_threshold)
print("Adjusted Monetary Threshold:", monetary_threshold)

Adjusted Frequency Anomalies Detected: [False False False False]
Adjusted Monetary Anomalies Detected: [False False False False]
Adjusted Frequency Threshold: None
Adjusted Monetary Threshold: None

In [71]:
# Adjusted anomaly threshold to 30%
def check_anomaly_threshold(percentile_dict, threshold=0.5):
    values = list(percentile_dict.values())
    diffs = np.diff(values) / np.array(values[:-1])
    return diffs > threshold

# Calculate anomalies
frequency_anomalies = check_anomaly_threshold(percentiles['Frequency'], threshold=0.5)
monetary_anomalies = check_anomaly_threshold(percentiles['Monetary'], threshold=0.5)

# Set thresholds again
if any(frequency_anomalies):
    frequency_threshold = list(percentiles['Frequency'].values())[-1]
else:
    frequency_threshold = max(percentiles['Frequency'].values())  # Fallback: Use the highest frequency percentile

if any(monetary_anomalies):
    monetary_threshold = list(percentiles['Monetary'].values())[-1]
else:
    monetary_threshold = max(percentiles['Monetary'].values())  # Fallback: Use the highest monetary percentile

# Debugging Outputs
print("Frequency Percentiles:", percentiles['Frequency'])
print("Frequency Anomalies Detected:", frequency_anomalies)
print("Frequency Threshold:", frequency_threshold)

print("Monetary Percentiles:", percentiles['Monetary'])
print("Monetary Anomalies Detected:", monetary_anomalies)
print("Monetary Threshold:", monetary_threshold)

# Step 4: Create a new column to mark anomalies
rfm_analysis['Anomaly'] = np.where(
    ((rfm_analysis['Frequency'] > frequency_threshold) & (frequency_threshold is not None)) |
    ((rfm_analysis['Monetary'] > monetary_threshold) & (monetary_threshold is not None)),
    'Anomalous',
    'Normal'
)

# Filter the anomalies into a separate DataFrame
rfm_anomalies = rfm_analysis[rfm_analysis['Anomaly'] == 'Anomalous']

# Remove anomalies from the original RFM analysis
rfm_analysis_filtered = rfm_analysis[rfm_analysis['Anomaly'] == 'Normal']

# Display results

Frequency Percentiles: {95: 202.0, 96: 215.0, 97: 230.0, 98: 248.0, 99: 274.2999999999993}
Frequency Anomalies Detected: [False False False False]
Frequency Threshold: 274.2999999999993
Monetary Percentiles: {95: 7381.1849999999995, 96: 7817.354000000001, 97: 8440.687999999998, 98: 9198.449999999995, 99: 10640.392999999991}
Monetary Anomalies Detected: [False False False False]
Monetary Threshold: 10640.392999999991

In [73]:
rfm_analysis_filtered

,id_customer,Recency,Frequency,Monetary,Monetary_net,Monetary_PL,First_Purchase,Last_Purchase,Avg_Interpurchase_Time,Std_Dev_Interpurchase_Time,Avg_Ticket,Std_Dev_Ticket,Anomaly
0,1,0,41,900.91,827.80,177.20,2021-01-04,2021-12-31,9.025000,10.146333,21.973415,16.485270,Normal
1,2,4,50,1229.57,980.41,404.31,2021-01-11,2021-12-27,7.142857,4.743416,24.591400,22.680259,Normal
2,3,8,20,1568.19,1083.57,56.00,2021-01-03,2021-12-23,18.631579,18.160429,78.409500,124.179337,Normal
3,4,0,74,4063.11,3348.90,865.91,2021-01-02,2021-12-31,4.972603,2.876980,54.906892,37.033964,Normal
4,5,2,121,5016.60,4331.09,651.12,2021-01-02,2021-12-29,3.008333,2.911859,41.459504,37.598486,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24993,24995,10,84,1984.01,1667.34,579.99,2021-01-06,2021-12-21,4.204819,4.080767,23.619167,15.743194,Normal
24994,24996,0,221,3074.26,2975.11,1645.51,2021-01-03,2021-12-31,1.645455,1.502426,13.910679,13.037960,Normal
24996,24998,0,90,3722.30,3192.02,1346.93,2021-01-05,2021-12-31,4.044944,2.499591,41.358889,28.744819,Normal
24997,24999,0,261,10022.70,8256.64,2938.74,2021-01-02,2021-12-31,1.396154,0.634273,38.401149,38.371012,Normal
24998,25000,9,36,3166.14,2849.25,775.18,2021-01-04,2021-12-22,10.057143,5.583288,87.948333,59.073081,Normal

In [76]:
import pandas as pd


# Step 1: Calculate Percentiles for R, F, and M
"it is better to use 0-5 days high 6-12 days medium and 12+ low as discussed in MA class
percentiles_rfm = {
    """
    'Recency': {
        'p20': rfm_analysis_filtered['Recency'].quantile(0.20),
        'p50': rfm_analysis_filtered['Recency'].quantile(0.50)
    },"""
    'Frequency': {
        'p50': rfm_analysis_filtered['Frequency'].quantile(0.50),
        'p80': rfm_analysis_filtered['Frequency'].quantile(0.80)
    },
    'Monetary': {
        'p50': rfm_analysis_filtered['Monetary'].quantile(0.50),
        'p80': rfm_analysis_filtered['Monetary'].quantile(0.80)
    }
}

# Step 2: Redefine the classify functions for R, F, M segmentation
"""
def classify_recency(value, percentiles):
    if value <= percentiles['p20']:
        return 'H'
    elif value <= percentiles['p50']:
        return 'M'
    else:
        return 'L'
"""
def classify_frequency(value, percentiles):
    if value > percentiles['p80']:
        return 'H'
    elif value > percentiles['p50']:
        return 'M'
    else:
        return 'L'

def classify_monetary(value, percentiles):
    if value > percentiles['p80']:
        return 'H'
    elif value > percentiles['p50']:
        return 'M'
    else:
        return 'L'

In [78]:
# Step 3: Apply the classification for Recency, Frequency, and Monetary

rfm_analysis_filtered['R'] = rfm_analysis['Recency'].apply(lambda x: 'H' if 0 <= x <= 5 else ('M' if x <= 12 else 'L'))


rfm_analysis_filtered['F'] = rfm_analysis_filtered['Frequency'].apply(
    lambda x: classify_frequency(x, percentiles_rfm['Frequency'])
)

rfm_analysis_filtered['M'] = rfm_analysis_filtered['Monetary'].apply(
    lambda x: classify_monetary(x, percentiles_rfm['Monetary'])
)

C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\1607337118.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm_analysis_filtered['R'] = rfm_analysis['Recency'].apply(lambda x: 'H' if 0 <= x <= 5 else ('M' if x <= 12 else 'L'))
C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\1607337118.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm_analysis_filtered['F'] = rfm_analysis_filtered['Frequency'].apply(
C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\1607337118.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm_analysis_filtered['M'] = rfm_analysis_filtered['Monetary'].apply(

In [80]:
rfm_analysis=rfm_analysis_filtered

In [82]:
# 1. Calculate the total gross sales for each customer
#rfm_analysis['gross_sales'] = df.groupby('id_customer')['gross_sales'].sum()

# 2. Analyze RFM in relation to PL (Private Label)
# Assuming PL_sales is a column representing sales attributed to the Private Label
#rfm_analysis['PL_gross_sales'] = df.groupby('id_customer')['PL_gross_sales'].sum()


# 3. Analyze the impact of PL_sales on Frequency
# Calculate a new column to represent the ratio of PL_sales to total sales
rfm_analysis['PL_Sales_Impact_on_Frequency'] = rfm_analysis['Monetary_PL'] / rfm_analysis['Frequency']

rfm_analysis['PL_sales_contribution'] = rfm_analysis['Monetary_PL'] / rfm_analysis['Monetary']

rfm_analysis['Net sales vs gross sales'] = rfm_analysis['Monetary_net'] / rfm_analysis['Monetary']

C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\2712585727.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm_analysis['PL_Sales_Impact_on_Frequency'] = rfm_analysis['Monetary_PL'] / rfm_analysis['Frequency']
C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\2712585727.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm_analysis['PL_sales_contribution'] = rfm_analysis['Monetary_PL'] / rfm_analysis['Monetary']
C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\2712585727.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm_analysis['Net sales vs gross sales'] = rfm_analysis['Monetary_net'] / rfm_analysis['Monetary']

In [84]:
rfm_analysis_filtered=rfm_analysis

In [86]:
rfm_analysis_filtered

,id_customer,Recency,Frequency,Monetary,Monetary_net,Monetary_PL,First_Purchase,Last_Purchase,Avg_Interpurchase_Time,Std_Dev_Interpurchase_Time,Avg_Ticket,Std_Dev_Ticket,Anomaly,R,F,M,PL_Sales_Impact_on_Frequency,PL_sales_contribution,Net sales vs gross sales
0,1,0,41,900.91,827.80,177.20,2021-01-04,2021-12-31,9.025000,10.146333,21.973415,16.485270,Normal,H,L,L,4.321951,0.196690,0.918849
1,2,4,50,1229.57,980.41,404.31,2021-01-11,2021-12-27,7.142857,4.743416,24.591400,22.680259,Normal,H,L,L,8.086200,0.328822,0.797360
2,3,8,20,1568.19,1083.57,56.00,2021-01-03,2021-12-23,18.631579,18.160429,78.409500,124.179337,Normal,M,L,L,2.800000,0.035710,0.690969
3,4,0,74,4063.11,3348.90,865.91,2021-01-02,2021-12-31,4.972603,2.876980,54.906892,37.033964,Normal,H,M,M,11.701486,0.213115,0.824221
4,5,2,121,5016.60,4331.09,651.12,2021-01-02,2021-12-29,3.008333,2.911859,41.459504,37.598486,Normal,H,H,H,5.381157,0.129793,0.863352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24993,24995,10,84,1984.01,1667.34,579.99,2021-01-06,2021-12-21,4.204819,4.080767,23.619167,15.743194,Normal,M,M,L,6.904643,0.292332,0.840389
24994,24996,0,221,3074.26,2975.11,1645.51,2021-01-03,2021-12-31,1.645455,1.502426,13.910679,13.037960,Normal,H,H,M,7.445747,0.535254,0.967748
24996,24998,0,90,3722.30,3192.02,1346.93,2021-01-05,2021-12-31,4.044944,2.499591,41.358889,28.744819,Normal,H,M,M,14.965889,0.361854,0.857540
24997,24999,0,261,10022.70,8256.64,2938.74,2021-01-02,2021-12-31,1.396154,0.634273,38.401149,38.371012,Normal,H,H,H,11.259540,0.293208,0.823794
24998,25000,9,36,3166.14,2849.25,775.18,2021-01-04,2021-12-22,10.057143,5.583288,87.948333,59.073081,Normal,M,L,M,21.532778,0.244834,0.899913

In [88]:
rfm_analysis_filtered[rfm_analysis_filtered['Recency']==12]

,id_customer,Recency,Frequency,Monetary,Monetary_net,Monetary_PL,First_Purchase,Last_Purchase,Avg_Interpurchase_Time,Std_Dev_Interpurchase_Time,Avg_Ticket,Std_Dev_Ticket,Anomaly,R,F,M,PL_Sales_Impact_on_Frequency,PL_sales_contribution,Net sales vs gross sales
2199,2200,12,62,1576.66,1200.83,651.09,2021-01-10,2021-12-19,5.622951,4.590439,25.430000,21.030348,Normal,M,M,L,10.501452,0.412955,0.761629
2351,2352,12,43,2775.82,2103.56,627.17,2021-01-10,2021-12-19,8.166667,5.834785,64.553953,37.205959,Normal,M,L,M,14.585349,0.225940,0.757816
2422,2423,12,19,842.91,702.54,105.28,2021-01-31,2021-12-19,17.888889,11.625979,44.363684,21.946528,Normal,M,L,L,5.541053,0.124901,0.833470
2432,2433,12,6,308.99,276.06,10.66,2021-01-24,2021-12-19,65.800000,65.074573,51.498333,22.658888,Normal,M,L,L,1.776667,0.034499,0.893427
2475,2476,12,30,1921.88,1435.68,341.34,2021-02-04,2021-12-19,10.965517,9.755887,64.062667,45.285545,Normal,M,L,L,11.378000,0.177607,0.747019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22383,22385,12,13,156.59,126.58,88.95,2021-01-05,2021-12-19,29.000000,35.957045,12.045385,6.502499,Normal,M,L,L,6.842308,0.568044,0.808353
22855,22857,12,72,1258.82,1087.10,654.59,2021-01-02,2021-12-19,4.943662,4.442931,17.483611,14.585966,Normal,M,M,L,9.091528,0.520003,0.863587
23411,23413,12,39,2233.51,2066.79,752.19,2021-01-11,2021-12-19,9.000000,7.501351,57.269487,68.547994,Normal,M,L,M,19.286923,0.336775,0.925355
23619,23621,12,62,1973.50,1840.04,679.08,2021-01-02,2021-12-19,5.754098,5.402641,31.830645,22.074464,Normal,M,M,L,10.952903,0.344099,0.932374
23871,23873,12,14,268.34,160.90,31.62,2021-05-11,2021-12-19,17.076923,13.883213,19.167143,36.477124,Normal,M,L,L,2.258571,0.117836,0.599612

In [90]:

# Define the RFM cluster descriptions with all detailed conditions as per the R example
def classify_rfm_cluster(row):
    if row['R'] == 'H' and row['F'] == 'H' and row['M'] == 'H':
        return "Champions"
    elif row['R'] == 'H' and row['F'] == 'M' and row['M'] == 'H':
        return "Champions"
    elif row['R'] == 'H' and row['F'] == 'H' and row['M'] == 'M':
        return "Champions"
    
    elif row['R'] == 'M' and row['F'] == 'H' and row['M'] == 'H':
        return "Loyal"
    elif row['R'] == 'M' and row['F'] == 'H' and row['M'] == 'M':
        return "Loyal"
    
    elif row['R'] == 'L' and row['F'] == 'M' and row['M'] == 'H':
        return "Cannot lose"
    elif row['R'] == 'L' and row['F'] == 'H' and row['M'] == 'H':
        return "Cannot lose"
    elif row['R'] == 'L' and row['F'] == 'H' and row['M'] == 'M':
        return "Cannot lose"
    
    elif row['R'] == 'H' and row['F'] == 'M' and row['M'] == 'M':
        return "Potential Loyalist"
    elif row['R'] == 'H' and row['F'] == 'M' and row['M'] == 'L':
        return "Potential Loyalist"
    elif row['R'] == 'H' and row['F'] == 'L' and row['M'] == 'M':
        return "Potential Loyalist"
    elif row['R'] == 'H' and row['F'] == 'H' and row['M'] == 'L':
        return "Potential Loyalist"
   
    elif row['R'] == 'H' and row['F'] == 'L' and row['M'] == 'L':
        return "As New"
    elif row['R'] == 'H' and row['F'] == 'L' and row['M'] == 'H':
        return "As New"
    elif row['R'] == 'M' and row['F'] == 'H' and row['M'] == 'L':
        return "As New"


    
    elif row['R'] == 'M' and row['F'] == 'L' and row['M'] == 'H':
        return "To Reactivate"
    elif row['R'] == 'M' and row['F'] == 'L' and row['M'] == 'M':
        return "To Reactivate"

    elif row['R'] == 'M' and row['F'] == 'M' and row['M'] == 'M':
        return "Searching for Attention"
    elif row['R'] == 'M' and row['F'] == 'M' and row['M'] == 'L':
        return "Searching for Attention"
        
    elif row['R'] == 'L' and row['F'] == 'L' and row['M'] == 'M':
        return "About to Sleep"
    elif row['R'] == 'L' and row['F'] == 'M' and row['M'] == 'M':
        return "About to Sleep"
    elif row['R'] == 'L' and row['F'] == 'L' and row['M'] == 'H':
        return "About to Sleep"
   
    elif row['R'] == 'L' and row['F'] == 'L' and row['M'] == 'M':
        return "Bad"
    elif row['R'] == 'L' and row['F'] == 'L' and row['M'] == 'L':
        return "Bad"
    elif row['R'] == 'M' and row['F'] == 'L' and row['M'] == 'L':
        return "Bad"
    elif row['R'] == 'L' and row['F'] == 'M' and row['M'] == 'L':
        return "Bad"
    else:
        return "Unknown"

# Apply the classification to the DataFrame
rfm_analysis_filtered['Cluster'] = rfm_analysis_filtered.apply(classify_rfm_cluster, axis=1)

C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\114633506.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm_analysis_filtered['Cluster'] = rfm_analysis_filtered.apply(classify_rfm_cluster, axis=1)

In [91]:
rfm_analysis_filtered

,id_customer,Recency,Frequency,Monetary,Monetary_net,Monetary_PL,First_Purchase,Last_Purchase,Avg_Interpurchase_Time,Std_Dev_Interpurchase_Time,Avg_Ticket,Std_Dev_Ticket,Anomaly,R,F,M,PL_Sales_Impact_on_Frequency,PL_sales_contribution,Net sales vs gross sales,Cluster
0,1,0,41,900.91,827.80,177.20,2021-01-04,2021-12-31,9.025000,10.146333,21.973415,16.485270,Normal,H,L,L,4.321951,0.196690,0.918849,As New
1,2,4,50,1229.57,980.41,404.31,2021-01-11,2021-12-27,7.142857,4.743416,24.591400,22.680259,Normal,H,L,L,8.086200,0.328822,0.797360,As New
2,3,8,20,1568.19,1083.57,56.00,2021-01-03,2021-12-23,18.631579,18.160429,78.409500,124.179337,Normal,M,L,L,2.800000,0.035710,0.690969,Bad
3,4,0,74,4063.11,3348.90,865.91,2021-01-02,2021-12-31,4.972603,2.876980,54.906892,37.033964,Normal,H,M,M,11.701486,0.213115,0.824221,Potential Loyalist
4,5,2,121,5016.60,4331.09,651.12,2021-01-02,2021-12-29,3.008333,2.911859,41.459504,37.598486,Normal,H,H,H,5.381157,0.129793,0.863352,Champions
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24993,24995,10,84,1984.01,1667.34,579.99,2021-01-06,2021-12-21,4.204819,4.080767,23.619167,15.743194,Normal,M,M,L,6.904643,0.292332,0.840389,Searching for Attention
24994,24996,0,221,3074.26,2975.11,1645.51,2021-01-03,2021-12-31,1.645455,1.502426,13.910679,13.037960,Normal,H,H,M,7.445747,0.535254,0.967748,Champions
24996,24998,0,90,3722.30,3192.02,1346.93,2021-01-05,2021-12-31,4.044944,2.499591,41.358889,28.744819,Normal,H,M,M,14.965889,0.361854,0.857540,Potential Loyalist
24997,24999,0,261,10022.70,8256.64,2938.74,2021-01-02,2021-12-31,1.396154,0.634273,38.401149,38.371012,Normal,H,H,H,11.259540,0.293208,0.823794,Champions
24998,25000,9,36,3166.14,2849.25,775.18,2021-01-04,2021-12-22,10.057143,5.583288,87.948333,59.073081,Normal,M,L,M,21.532778,0.244834,0.899913,To Reactivate

In [92]:
rfm_analysis_filtered.isnull().sum()

id_customer                       0
Recency                           0
Frequency                         0
Monetary                          0
Monetary_net                      0
Monetary_PL                       0
First_Purchase                    0
Last_Purchase                     0
Avg_Interpurchase_Time            0
Std_Dev_Interpurchase_Time      148
Avg_Ticket                        0
Std_Dev_Ticket                    0
Anomaly                           0
R                                 0
F                                 0
M                                 0
PL_Sales_Impact_on_Frequency      0
PL_sales_contribution             0
Net sales vs gross sales          0
Cluster                           0
dtype: int64

In [96]:
rfm_analysis_filtered

,id_customer,Recency,Frequency,Monetary,Monetary_net,Monetary_PL,First_Purchase,Last_Purchase,Avg_Interpurchase_Time,Std_Dev_Interpurchase_Time,Avg_Ticket,Std_Dev_Ticket,Anomaly,R,F,M,PL_Sales_Impact_on_Frequency,PL_sales_contribution,Net sales vs gross sales,Cluster
0,1,0,41,900.91,827.80,177.20,2021-01-04,2021-12-31,9.025000,10.146333,21.973415,16.485270,Normal,H,L,L,4.321951,0.196690,0.918849,As New
1,2,4,50,1229.57,980.41,404.31,2021-01-11,2021-12-27,7.142857,4.743416,24.591400,22.680259,Normal,H,L,L,8.086200,0.328822,0.797360,As New
2,3,8,20,1568.19,1083.57,56.00,2021-01-03,2021-12-23,18.631579,18.160429,78.409500,124.179337,Normal,M,L,L,2.800000,0.035710,0.690969,Bad
3,4,0,74,4063.11,3348.90,865.91,2021-01-02,2021-12-31,4.972603,2.876980,54.906892,37.033964,Normal,H,M,M,11.701486,0.213115,0.824221,Potential Loyalist
4,5,2,121,5016.60,4331.09,651.12,2021-01-02,2021-12-29,3.008333,2.911859,41.459504,37.598486,Normal,H,H,H,5.381157,0.129793,0.863352,Champions
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24993,24995,10,84,1984.01,1667.34,579.99,2021-01-06,2021-12-21,4.204819,4.080767,23.619167,15.743194,Normal,M,M,L,6.904643,0.292332,0.840389,Searching for Attention
24994,24996,0,221,3074.26,2975.11,1645.51,2021-01-03,2021-12-31,1.645455,1.502426,13.910679,13.037960,Normal,H,H,M,7.445747,0.535254,0.967748,Champions
24996,24998,0,90,3722.30,3192.02,1346.93,2021-01-05,2021-12-31,4.044944,2.499591,41.358889,28.744819,Normal,H,M,M,14.965889,0.361854,0.857540,Potential Loyalist
24997,24999,0,261,10022.70,8256.64,2938.74,2021-01-02,2021-12-31,1.396154,0.634273,38.401149,38.371012,Normal,H,H,H,11.259540,0.293208,0.823794,Champions
24998,25000,9,36,3166.14,2849.25,775.18,2021-01-04,2021-12-22,10.057143,5.583288,87.948333,59.073081,Normal,M,L,M,21.532778,0.244834,0.899913,To Reactivate

In [98]:
cluster_counts = rfm_analysis_filtered['Cluster'].value_counts()
cluster_counts

Cluster
Potential Loyalist         6109
Bad                        5691
Champions                  5561
As New                     4199
To Reactivate               941
Searching for Attention     916
About to Sleep              396
Unknown                     254
Loyal                       250
Cannot lose                  86
Name: count, dtype: int64

In [100]:
# Regularity Analysis for Frequency (F)
rfm_analysis_filtered['Interpurchase_CV'] = rfm_analysis_filtered.apply(
    lambda row: (row['Std_Dev_Interpurchase_Time'] / row['Avg_Interpurchase_Time']
                 if pd.notnull(row['Std_Dev_Interpurchase_Time']) and row['Avg_Interpurchase_Time'] > 0 else None),
    axis=1
)

rfm_analysis_filtered['Regularity_F'] = rfm_analysis_filtered['Interpurchase_CV'].apply(
    lambda x: 'Highly Regular' if pd.notnull(x) and x <= 0.5 else
              'Moderately Regular' if pd.notnull(x) and x <= 1.0 else
              'Moderately Irregular' if pd.notnull(x) and x <= 1.5 else
              'Highly Irregular' if pd.notnull(x) and x > 1.5 else
              'Unknown'
)

# Regularity Analysis for Monetary (M)
rfm_analysis_filtered['Monetary_CV'] = rfm_analysis_filtered.apply(
    lambda row: (row['Std_Dev_Ticket'] / row['Avg_Ticket']
                 if pd.notnull(row['Std_Dev_Ticket']) and row['Avg_Ticket'] > 0 else None),
    axis=1
)

rfm_analysis_filtered['Regularity_M'] = rfm_analysis_filtered['Monetary_CV'].apply(
    lambda x: 'Highly Regular' if pd.notnull(x) and x <= 0.5 else
              'Moderately Regular' if pd.notnull(x) and x <= 1.0 else
              'Moderately Irregular' if pd.notnull(x) and x <= 1.5 else
              'Highly Irregular' if pd.notnull(x) and x > 1.5 else
              'Unknown'
)

# Regularity Analysis for Recency (R)
rfm_analysis_filtered['R_Subjective'] = rfm_analysis_filtered.apply(
    lambda row: 'H' if row['Recency'] <= row['Avg_Interpurchase_Time'] else
                'M' if row['Recency'] <= row['Avg_Interpurchase_Time'] + row['Std_Dev_Interpurchase_Time'] else
                'L' if row['Recency'] > row['Avg_Interpurchase_Time'] + row['Std_Dev_Interpurchase_Time'] else
                'Unknown',
    axis=1
)

# Display updated DataFrame
rfm_analysis_filtered

C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\3642750156.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm_analysis_filtered['Interpurchase_CV'] = rfm_analysis_filtered.apply(
C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\3642750156.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm_analysis_filtered['Regularity_F'] = rfm_analysis_filtered['Interpurchase_CV'].apply(
C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\3642750156.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm_analysis_filtered['Monetary_CV'] = rfm_analysis_filtered.apply(
C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\3642750156.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm_analysis_filtered['Regularity_M'] = rfm_analysis_filtered['Monetary_CV'].apply(
C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\3642750156.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm_analysis_filtered['R_Subjective'] = rfm_analysis_filtered.apply(

,id_customer,Recency,Frequency,Monetary,Monetary_net,Monetary_PL,First_Purchase,Last_Purchase,Avg_Interpurchase_Time,Std_Dev_Interpurchase_Time,...,M,PL_Sales_Impact_on_Frequency,PL_sales_contribution,Net sales vs gross sales,Cluster,Interpurchase_CV,Regularity_F,Monetary_CV,Regularity_M,R_Subjective
0,1,0,41,900.91,827.80,177.20,2021-01-04,2021-12-31,9.025000,10.146333,...,L,4.321951,0.196690,0.918849,As New,1.124247,Moderately Irregular,0.750237,Moderately Regular,H
1,2,4,50,1229.57,980.41,404.31,2021-01-11,2021-12-27,7.142857,4.743416,...,L,8.086200,0.328822,0.797360,As New,0.664078,Moderately Regular,0.922284,Moderately Regular,H
2,3,8,20,1568.19,1083.57,56.00,2021-01-03,2021-12-23,18.631579,18.160429,...,L,2.800000,0.035710,0.690969,Bad,0.974712,Moderately Regular,1.583728,Highly Irregular,H
3,4,0,74,4063.11,3348.90,865.91,2021-01-02,2021-12-31,4.972603,2.876980,...,M,11.701486,0.213115,0.824221,Potential Loyalist,0.578566,Moderately Regular,0.674487,Moderately Regular,H
4,5,2,121,5016.60,4331.09,651.12,2021-01-02,2021-12-29,3.008333,2.911859,...,H,5.381157,0.129793,0.863352,Champions,0.967931,Moderately Regular,0.906873,Moderately Regular,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24993,24995,10,84,1984.01,1667.34,579.99,2021-01-06,2021-12-21,4.204819,4.080767,...,L,6.904643,0.292332,0.840389,Searching for Attention,0.970498,Moderately Regular,0.666543,Moderately Regular,L
24994,24996,0,221,3074.26,2975.11,1645.51,2021-01-03,2021-12-31,1.645455,1.502426,...,M,7.445747,0.535254,0.967748,Champions,0.913077,Moderately Regular,0.937263,Moderately Regular,H
24996,24998,0,90,3722.30,3192.02,1346.93,2021-01-05,2021-12-31,4.044944,2.499591,...,M,14.965889,0.361854,0.857540,Potential Loyalist,0.617955,Moderately Regular,0.695009,Moderately Regular,H
24997,24999,0,261,10022.70,8256.64,2938.74,2021-01-02,2021-12-31,1.396154,0.634273,...,H,11.259540,0.293208,0.823794,Champions,0.454300,Highly Regular,0.999215,Moderately Regular,H
24998,25000,9,36,3166.14,2849.25,775.18,2021-01-04,2021-12-22,10.057143,5.583288,...,M,21.532778,0.244834,0.899913,To Reactivate,0.555157,Moderately Regular,0.671679,Moderately Regular,H

In [102]:
import matplotlib.pyplot as plt
%matplotlib qt
import seaborn as sns
import pandas as pd

In [106]:
df = rfm_analysis_filtered.copy()
%matplotlib qt

# 1. Distribution of Recency, Frequency, and Monetary values
plt.figure()
sns.histplot(df['Recency'], kde=True, bins=30, color='blue')
plt.title('Distribution of Recency')
plt.figure()
sns.histplot(df['Frequency'], kde=True, bins=30, color='green')
plt.title('Distribution of Frequency')
plt.figure()
sns.histplot(df['Monetary'], kde=True, bins=30, color='red')
plt.title('Distribution of Monetary')

Text(0.5, 1.0, 'Distribution of Monetary')

In [108]:
%matplotlib qt

# 1. Distribution of R, F, M values
plt.figure()
sns.histplot(df['R'], kde=False, bins=30, color='blue')
plt.title('Distribution of Recency', fontsize=14)
plt.xlabel('Recency', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.tight_layout()

plt.figure()
sns.histplot(df['F'], kde=False, bins=30, color='green')
plt.title('Distribution of Frequency', fontsize=14)
plt.xlabel('Frequency', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.tight_layout()

plt.figure()
sns.histplot(df['M'], kde=False, bins=30, color='red')
plt.title('Distribution of Monetary', fontsize=14)
plt.xlabel('Monetary', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.tight_layout()

In [ ]:

# 2. Count of Customers in Each RFM Segment (Cluster column)
plt.figure()
sns.countplot(data=df, y='Cluster', order=df['Cluster'].value_counts().index, palette='viridis')
plt.title('Count of Customers in Each RFM Segment', fontsize=14)
plt.xlabel('Number of Customers', fontsize=12)
plt.ylabel('Cluster', fontsize=12)
plt.xticks(fontsize=10)
plt.yticks(fontsize=10)
plt.tight_layout()

# 3. Monetary distribution across Regularity_F
plt.figure()
sns.boxplot(data=df, x='Monetary_CV', y='Monetary', palette='pastel')
plt.title('Monetary Value Across Monetary CV', fontsize=14)
plt.xlabel('Monetary CV', fontsize=12)
plt.ylabel('Monetary Value', fontsize=12)
plt.xticks(fontsize=10)
plt.yticks(fontsize=10)
plt.tight_layout()

C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\3886512902.py:3: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

  sns.countplot(data=df, y='Cluster', order=df['Cluster'].value_counts().index, palette='viridis')
C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\3886512902.py:13: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(data=df, x='Monetary_CV', y='Monetary', palette='pastel')

In [124]:
%matplotlib qt

# 5. Recency and Frequency Comparison (Scatterplot)
plt.figure()
sns.scatterplot(data=df, x='Recency', y='Frequency', hue='Cluster', palette='tab10')
plt.title('Recency vs Frequency by Cluster', fontsize=14)
plt.xlabel('Recency', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.xticks(fontsize=10)
plt.yticks(fontsize=10)
plt.legend(title='Cluster', fontsize=10)
plt.tight_layout()


# 5. Recency and Frequency Comparison (Scatterplot)
plt.figure()
sns.scatterplot(data=df, x='Frequency', y='Monetary', hue='Cluster', palette='tab10')
plt.title('Frequency vs Monetary', fontsize=20)
plt.xlabel('Frequency', fontsize=18)
plt.ylabel('Monetary', fontsize=18)
plt.xticks(fontsize=10)
plt.yticks(fontsize=10)
plt.legend(title='Cluster', fontsize=18)
plt.tight_layout()


# 6. Average Interpurchase Time by Cluster
plt.figure()
sns.barplot(data=df, x='Cluster', y='Avg_Interpurchase_Time', palette='coolwarm')
plt.title('Average Interpurchase Time by Cluster', fontsize=14)
plt.xlabel('Cluster', fontsize=10)
plt.ylabel('Average Interpurchase Time', fontsize=12)
plt.xticks(rotation=40, fontsize=10)
plt.yticks(fontsize=10)
plt.tight_layout()

# 7. Standard Deviation of Interpurchase Time by Cluster
plt.figure()
sns.barplot(data=df, x='Cluster', y='Std_Dev_Interpurchase_Time', palette='viridis')
plt.title('Standard Deviation of Interpurchase Time by Cluster', fontsize=14)
plt.xlabel('Cluster', fontsize=12)
plt.ylabel('Standard Deviation of Interpurchase Time', fontsize=12)
plt.xticks(rotation=45, fontsize=10)
plt.yticks(fontsize=10)
plt.tight_layout()

C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\3218448395.py:29: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(data=df, x='Cluster', y='Avg_Interpurchase_Time', palette='coolwarm')
C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\3218448395.py:39: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(data=df, x='Cluster', y='Std_Dev_Interpurchase_Time', palette='viridis')

In [118]:
# Ensure interactive plotting
%matplotlib qt


# 3. Monetary vs Monetary_PL (Stacked Bar Chart for PL_sales_contribution)
df_grouped = df.groupby('Cluster').agg({'Monetary': 'sum', 'Monetary_PL': 'sum'}).reset_index()
df_grouped['Non_PL'] = df_grouped['Monetary'] - df_grouped['Monetary_PL']

plt.figure(figsize=(12, 6))
df_grouped[['Cluster', 'Monetary_PL', 'Non_PL']].set_index('Cluster').plot(
    kind='bar', stacked=True, figsize=(12, 6), color=['#1f77b4', '#ff7f0e']
)
plt.title('Stacked Bar Chart: Monetary vs Monetary_PL', fontsize=14)
plt.ylabel('Sales', fontsize=12)
plt.xlabel('Cluster', fontsize=12)
plt.xticks(rotation=45, fontsize=10)
plt.legend(['Monetary_PL', 'Non_PL'], title='Sales Type')
plt.tight_layout()

# 4. PL_sales_contribution by Cluster (Bar Plot)
plt.figure(figsize=(12, 6))
sns.barplot(
    data=df, x='Cluster', y='PL_sales_contribution', estimator='mean', palette='coolwarm',
    order=df['Cluster'].value_counts().index
)
plt.title('PL Sales Contribution by Cluster', fontsize=14)
plt.ylabel('PL Sales Contribution (%)', fontsize=12)
plt.xlabel('Cluster', fontsize=12)
plt.xticks(rotation=45, fontsize=10)
plt.yticks(fontsize=10)
plt.tight_layout()

# 5. Correlation heatmap for numeric columns
numeric_cols = ['Recency', 'Frequency', 'Monetary', 'Monetary_PL', 'PL_sales_contribution','Avg_Interpurchase_Time','Std_Dev_Interpurchase_Time','Interpurchase_CV','Monetary_CV']
correlation_matrix = df[numeric_cols].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, fmt='.2f', cmap='coolwarm', cbar=True)
plt.title('Correlation Heatmap', fontsize=18)
plt.xticks(fontsize=10, rotation=45)
plt.yticks(fontsize=10)
plt.tight_layout()

# Show all plots
plt.show()

C:\Users\kaant\AppData\Local\Temp\ipykernel_29548\433070361.py:22: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(

In [107]:
# Ensure plots open in separate windows
%matplotlib qt

# Add a derived column for Monetary percentage from PL (PL_sales_contribution)
df['PL_sales_contribution_percentage'] = (df['Monetary_PL'] / df['Monetary']) * 100

# 1. Monetary vs Monetary_PL Stacked Bar Chart (Cluster Level)
df_grouped = df.groupby('Cluster').agg({'Monetary': 'sum', 'Monetary_PL': 'sum'}).reset_index()
df_grouped['Non_PL'] = df_grouped['Monetary'] - df_grouped['Monetary_PL']

plt.figure(figsize=(12, 6))
df_grouped[['Cluster', 'Monetary_PL', 'Non_PL']].set_index('Cluster').plot(
    kind='bar', stacked=True, figsize=(12, 6), color=['#1f77b4', '#ff7f0e']
)
plt.title('Monetary vs Monetary_PL Contribution by Cluster', fontsize=14)
plt.ylabel('Sales', fontsize=12)
plt.xlabel('Cluster', fontsize=12)
plt.xticks(rotation=45, fontsize=10)
plt.legend(['PL Sales (Monetary_PL)', 'Non-PL Sales'], title='Sales Type')
plt.tight_layout()
plt.show()

# 2. Count of Customers and Percentage of PL Sales by Cluster
df['PL_sales_category'] = pd.cut(
    df['PL_sales_contribution'], bins=[0, 0.25, 0.5, 0.75, 1], labels=['Low', 'Medium', 'High', 'Very High']
)

# Group by Cluster and PL_sales_category
cluster_pl_count = df.groupby(['Cluster', 'PL_sales_category']).size().unstack(fill_value=0)
cluster_pl_percentage = cluster_pl_count.div(cluster_pl_count.sum(axis=1), axis=0) * 100

# Plot count as a stacked bar chart
plt.figure(figsize=(12, 6))
cluster_pl_count.plot(
    kind='bar', stacked=True, figsize=(12, 6), colormap='viridis'
)
plt.title('Count of Customers by PL Sales Contribution Categories and Cluster', fontsize=14)
plt.ylabel('Number of Customers', fontsize=12)
plt.xlabel('Cluster', fontsize=12)
plt.xticks(rotation=45, fontsize=10)
plt.legend(title='PL Sales Contribution')
plt.tight_layout()
plt.show()

# Plot percentage as a stacked bar chart
plt.figure(figsize=(12, 6))
cluster_pl_percentage.plot(
    kind='bar', stacked=True, figsize=(12, 6), colormap='coolwarm'
)
plt.title('Percentage of PL Sales Contribution Categories by Cluster', fontsize=14)
plt.ylabel('Percentage of Customers (%)', fontsize=12)
plt.xlabel('Cluster', fontsize=12)
plt.xticks(rotation=45, fontsize=10)
plt.legend(title='PL Sales Contribution')
plt.tight_layout()
plt.show()

# 5. Ratio of PL vs Non-PL Sales by Cluster (Percentage)
df_grouped['PL_Percentage'] = (df_grouped['Monetary_PL'] / df_grouped['Monetary']) * 100
df_grouped['Non_PL_Percentage'] = 100 - df_grouped['PL_Percentage']

plt.figure(figsize=(12, 6))
df_grouped[['Cluster', 'PL_Percentage', 'Non_PL_Percentage']].set_index('Cluster').plot(
    kind='bar', stacked=True, figsize=(12, 6), color=['#1f77b4',

C:\Users\kaant\anaconda3\Lib\site-packages\pandas\plotting\_matplotlib\core.py:580: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  fig = self.plt.figure(figsize=self.figsize)
C:\Users\kaant\AppData\Local\Temp\ipykernel_27612\1895941890.py:28: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  cluster_pl_count = df.groupby(['Cluster', 'PL_sales_category']).size().unstack(fill_value=0)

In [109]:

%matplotlib qt

# Ensure plots open in separate tabs
%matplotlib qt

# 2. Stacked Bar Chart: Monetary and Monetary_Net by Cluster
df_grouped = df.groupby('Cluster').agg({'Monetary': 'sum', 'Monetary_net': 'sum'}).reset_index()
df_grouped['Non_Monetary_Net'] = df_grouped['Monetary'] - df_grouped['Monetary_net']

plt.figure(figsize=(12, 6))
df_grouped[['Cluster', 'Monetary_net', 'Non_Monetary_Net']].set_index('Cluster').plot(
    kind='bar', stacked=True, figsize=(12, 6), color=['#1f77b4', '#ff7f0e']
)
plt.title('Monetary vs Monetary_Net Contribution by Cluster', fontsize=14)
plt.ylabel('Total Sales', fontsize=12)
plt.xlabel('Cluster', fontsize=12)
plt.xticks(rotation=45, fontsize=10)
plt.legend(['Monetary_Net', 'Non-Monetary_Net'], title='Sales Type')
plt.tight_layout()
plt.show()

# 3. Distribution of Monetary and Monetary_Net
plt.figure(figsize=(10, 6))
sns.kdeplot(data=df, x='Monetary', fill=True, color='blue', alpha=0.4, label='Monetary')
sns.kdeplot(data=df, x='Monetary_net', fill=True, color='green', alpha=0.4, label='Monetary_Net')
plt.title('Distribution of Monetary and Monetary_Net', fontsize=14)
plt.xlabel('Sales Value', fontsize=12)
plt.ylabel('Density', fontsize=12)
plt.legend(title='Sales Type')
plt.tight_layout()
plt.show()

In [ ]:
rfm_analysis_filtered

In [93]:
df_rfm = rfm_analysis_filtered.copy()  # Replace with your actual DataFrame

# Save to Excel
df_rfm.to_excel('rfm_analysis_final_1.xlsx', index=False, sheet_name='RFM_Data')

print("DataFrame successfully saved to 'rfm_analysis.xlsx'")

DataFrame successfully saved to 'rfm_analysis.xlsx'